# Introduction to NumPy
- Creating arrays
- Multi-dimentional arrays
- Randomly generated arrays
- Element-wise operations
  - Comparison operations
  - Logical operations
- Summarizing operations

In [1]:
import numpy as np

# Creating arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [7]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimensional arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0,1]

np.int64(2)

In [17]:
n[0]

array([1, 2, 3])

In [19]:
n[:,1]

array([2, 5, 8])

# Randomly generated arrays

In [21]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise Operations

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
a+1 #Any operation can be used in place of + (Can use any expression also)

array([1, 2, 3, 4, 5])

## Comparison operations

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [29]:
a[a>2]

array([3, 4])

## Summarization Operations

In [30]:
a.min()

np.int64(0)

In [31]:
a.max()

np.int64(4)

In [32]:
a.sum()

np.int64(10)

In [33]:
a.std()

np.float64(1.4142135623730951)