# Introduction to NumPy
- Creating arrays
- Multi-dimentional arrays
- Randomly generated arrays
- Element-wise operations
  - Comparison operations
  - Logical operations
- Summarizing operations

In [1]:
import numpy as np

# Creating arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [5]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimensional arrays

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
n[0,1]

np.int64(2)

In [12]:
n[0]

array([1, 2, 3])

In [13]:
n[:,1]

array([2, 5, 8])

# Randomly generated arrays

In [14]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [15]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [16]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise Operations

In [17]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [18]:
a+1 #Any operation can be used in place of + (Can use any expression also)

array([1, 2, 3, 4, 5])

## Comparison operations

In [19]:
a >= 2

array([False, False,  True,  True,  True])

In [20]:
a[a>2]

array([3, 4])

## Summarization Operations

In [21]:
a.min()

np.int64(0)

In [22]:
a.max()

np.int64(4)

In [23]:
a.sum()

np.int64(10)

In [24]:
a.std()

np.float64(1.4142135623730951)

# Linear Algebra

## Multiplication

In [25]:
u = np.array([1,2,3,4])
v = np.array([2,5,7,8])

In [26]:
u.shape[0]

4

In [27]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i]*v[i]

    return result

In [28]:
vector_vector_multiplication(u,v)

np.float64(65.0)

In [29]:
u.dot(v)

np.int64(65)

In [30]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [31]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [32]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [33]:
matrix_vector_multiplication(U,v)

array([107.,  35.,  33.])

In [36]:
U.dot(v)

array([107,  35,  33])

In [37]:
U.shape

(3, 4)

In [38]:
V.shape

(4, 3)

In [35]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [39]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:,i] = Uvi

    return result

In [40]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [41]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [44]:
I = np.eye(3)

In [46]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [45]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [48]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [51]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [52]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])